apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
  namespace: javalearner-new
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8082
  type: NodePort
